name: reactable
description: a reactive state management library that automatically updates the UI when values of an reactable objects change .It is easy, light, fast and well tested.
repository: https://github.com/SchabanBo/reactable
version: 0.1.4

environment:
  sdk: '>=2.16.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
 
flutter:
